import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js — don't use client-side code here (browser APIs, JSX...).

const sidebars: SidebarsConfig = {
  // The docs sidebar is generated from the docs folder structure.
  docsSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
